python src/2/naiveBayesClassifier.py 1
python src/2/naiveBayesClassifier.py 2
python src/2/naiveBayesClassifier.py 3
python src/2/naiveBayesClassifier.py 4
python src/2/naiveBayesClassifier.py 5
python src/2/naiveBayesClassifier.py 6
python src/2/naiveBayesClassifier.py 7
python src/2/naiveBayesClassifier.py 8
python src/2/naiveBayesClassifier.py 9
python src/2/naiveBayesClassifier.py 10
